memory_unit          decr                                      2   5 2
memory_unit          decr64                                    2   5 2
memory_unit          incr                                      2   7 2
memory_unit          incr64                                    2   7 2
memory_unit          add                                       7   7 0
memory_unit          add32_var_sat_metering                    7  30 0
memory_unit          add64                                     7   7 0
memory_unit          add64_imm                                 7   7 2
memory_unit          add64_imm_sat                             7   8 2
memory_unit          add64_sat                                 7   8 0
memory_unit          add64_var_sat_metering                    7  30 0
memory_unit          add_imm                                   7   7 2
memory_unit          add_imm_sat                               7   8 2
memory_unit          add_sat                                   7   8 0
memory_unit          add_tail                                  7  19 0
memory_unit          addsat                                    7   8 0
memory_unit          addsat64                                  7   8 0
memory_unit          addsat64_imm                              7   8 2
memory_unit          addsat_imm                                7   8 2
memory_unit          atomic_read                               7  34 0
memory_unit          atomic_write                              7   4 0
memory_unit          atomic_write_imm                          7   4 2
memory_unit          cam1024_lookup16_add_inc                  7  36 0
memory_unit          cam1024_lookup16_inc_wo_add               7  36 1
memory_unit          cam1024_lookup18_add_inc                  7  36 2
memory_unit          cam1024_lookup18_inc_wo_add               7  36 3
memory_unit          cam1024_lookup20_add_inc                  7  36 2
memory_unit          cam1024_lookup20_inc_wo_add               7  36 3
memory_unit          cam1024_lookup24_add_inc                  7  36 0
memory_unit          cam1024_lookup24_inc_wo_add               7  36 1
memory_unit          cam1024_lookup48_add_inc                  7  36 0
memory_unit          cam1024_lookup48_inc_wo_add               7  36 1
memory_unit          cam128_lookup16                           7  12 0
memory_unit          cam128_lookup16_add                       7  12 2
memory_unit          cam128_lookup16_add_inc                   7  36 0
memory_unit          cam128_lookup16_inc_wo_add                7  36 1
memory_unit          cam128_lookup18_add_inc                   7  36 2
memory_unit          cam128_lookup18_inc_wo_add                7  36 3
memory_unit          cam128_lookup20_add_inc                   7  36 2
memory_unit          cam128_lookup20_inc_wo_add                7  36 3
memory_unit          cam128_lookup24                           7  12 0
memory_unit          cam128_lookup24_add                       7  12 2
memory_unit          cam128_lookup24_add_inc                   7  36 0
memory_unit          cam128_lookup24_inc_wo_add                7  36 1
memory_unit          cam128_lookup32                           7  12 0
memory_unit          cam128_lookup32_add                       7  12 2
memory_unit          cam128_lookup48_add_inc                   7  36 0
memory_unit          cam128_lookup48_inc_wo_add                7  36 1
memory_unit          cam128_lookup8                            7  12 0
memory_unit          cam128_lookup8_add                        7  12 2
memory_unit          cam256_lookup16                           7  12 0
memory_unit          cam256_lookup16_add                       7  12 2
memory_unit          cam256_lookup16_add_inc                   7  36 0
memory_unit          cam256_lookup16_inc_wo_add                7  36 1
memory_unit          cam256_lookup18_add_inc                   7  36 2
memory_unit          cam256_lookup18_inc_wo_add                7  36 3
memory_unit          cam256_lookup20_add_inc                   7  36 2
memory_unit          cam256_lookup20_inc_wo_add                7  36 3
memory_unit          cam256_lookup24                           7  12 0
memory_unit          cam256_lookup24_add                       7  12 2
memory_unit          cam256_lookup24_add_inc                   7  36 0
memory_unit          cam256_lookup24_inc_wo_add                7  36 1
memory_unit          cam256_lookup32                           7  12 0
memory_unit          cam256_lookup32_add                       7  12 2
memory_unit          cam256_lookup48_add_inc                   7  36 0
memory_unit          cam256_lookup48_inc_wo_add                7  36 1
memory_unit          cam256_lookup8                            7  12 0
memory_unit          cam256_lookup8_add                        7  12 2
memory_unit          cam384_lookup16                           7  12 0
memory_unit          cam384_lookup16_add                       7  12 2
memory_unit          cam384_lookup16_add_inc                   7  36 0
memory_unit          cam384_lookup16_inc_wo_add                7  36 1
memory_unit          cam384_lookup18_add_inc                   7  36 2
memory_unit          cam384_lookup18_inc_wo_add                7  36 3
memory_unit          cam384_lookup20_add_inc                   7  36 2
memory_unit          cam384_lookup20_inc_wo_add                7  36 3
memory_unit          cam384_lookup24                           7  12 0
memory_unit          cam384_lookup24_add                       7  12 2
memory_unit          cam384_lookup24_add_inc                   7  36 0
memory_unit          cam384_lookup24_inc_wo_add                7  36 1
memory_unit          cam384_lookup32                           7  12 0
memory_unit          cam384_lookup32_add                       7  12 2
memory_unit          cam384_lookup48_add_inc                   7  36 0
memory_unit          cam384_lookup48_inc_wo_add                7  36 1
memory_unit          cam384_lookup8                            7  12 0
memory_unit          cam384_lookup8_add                        7  12 2
memory_unit          cam512_lookup16                           7  12 0
memory_unit          cam512_lookup16_add                       7  12 2
memory_unit          cam512_lookup16_add_inc                   7  36 0
memory_unit          cam512_lookup16_inc_wo_add                7  36 1
memory_unit          cam512_lookup18_add_inc                   7  36 2
memory_unit          cam512_lookup18_inc_wo_add                7  36 3
memory_unit          cam512_lookup20_add_inc                   7  36 2
memory_unit          cam512_lookup20_inc_wo_add                7  36 3
memory_unit          cam512_lookup24                           7  12 0
memory_unit          cam512_lookup24_add                       7  12 2
memory_unit          cam512_lookup24_add_inc                   7  36 0
memory_unit          cam512_lookup24_inc_wo_add                7  36 1
memory_unit          cam512_lookup32                           7  12 0
memory_unit          cam512_lookup32_add                       7  12 2
memory_unit          cam512_lookup48_add_inc                   7  36 0
memory_unit          cam512_lookup48_inc_wo_add                7  36 1
memory_unit          cam512_lookup8                            7  12 0
memory_unit          cam512_lookup8_add                        7  12 2
memory_unit          cam640_lookup16_add_inc                   7  36 0
memory_unit          cam640_lookup16_inc_wo_add                7  36 1
memory_unit          cam640_lookup18_add_inc                   7  36 2
memory_unit          cam640_lookup18_inc_wo_add                7  36 3
memory_unit          cam640_lookup20_add_inc                   7  36 2
memory_unit          cam640_lookup20_inc_wo_add                7  36 3
memory_unit          cam640_lookup24_add_inc                   7  36 0
memory_unit          cam640_lookup24_inc_wo_add                7  36 1
memory_unit          cam640_lookup48_add_inc                   7  36 0
memory_unit          cam640_lookup48_inc_wo_add                7  36 1
memory_unit          cam768_lookup16_add_inc                   7  36 0
memory_unit          cam768_lookup16_inc_wo_add                7  36 1
memory_unit          cam768_lookup18_add_inc                   7  36 2
memory_unit          cam768_lookup18_inc_wo_add                7  36 3
memory_unit          cam768_lookup20_add_inc                   7  36 2
memory_unit          cam768_lookup20_inc_wo_add                7  36 3
memory_unit          cam768_lookup24_add_inc                   7  36 0
memory_unit          cam768_lookup24_inc_wo_add                7  36 1
memory_unit          cam768_lookup48_add_inc                   7  36 0
memory_unit          cam768_lookup48_inc_wo_add                7  36 1
memory_unit          cam896_lookup16_add_inc                   7  36 0
memory_unit          cam896_lookup16_inc_wo_add                7  36 1
memory_unit          cam896_lookup18_add_inc                   7  36 2
memory_unit          cam896_lookup18_inc_wo_add                7  36 3
memory_unit          cam896_lookup20_add_inc                   7  36 2
memory_unit          cam896_lookup20_inc_wo_add                7  36 3
memory_unit          cam896_lookup24_add_inc                   7  36 0
memory_unit          cam896_lookup24_inc_wo_add                7  36 1
memory_unit          cam896_lookup48_add_inc                   7  36 0
memory_unit          cam896_lookup48_inc_wo_add                7  36 1
memory_unit          cam_lookup                                7  12 0
memory_unit          cam_lookup_add                            7  12 2
memory_unit          cam_lookup_add_extend                     7  29 2
memory_unit          cam_lookup_add_lock                       7  29 1
memory_unit          clr                                       7   6 0
memory_unit          clr_imm                                   7   6 2
memory_unit          compare_write                             7  34 2
memory_unit          crc32                                     7  37 0
memory_unit          crc32_imm                                 7  37 1
memory_unit          crc32c                                    7  37 2
memory_unit          crc32c_imm                                7  37 3
memory_unit          csum16_inv                                7  27 0
memory_unit          csum16_no_inv                             7  27 1
memory_unit          dequeue                                   7  17 2
memory_unit          enqueue                                   7  17 0
memory_unit          enqueue_tail                              7  17 1
memory_unit          fast_journal                              7  23 0
memory_unit          fast_journal_sig                          7  23 1
memory_unit          get                                       7  21 0
memory_unit          get_eop                                   7  21 1
memory_unit          get_freely                                7  21 2
memory_unit          get_safe                                  7  21 2
memory_unit          journal                                   7  20 2
memory_unit          lock128                                   7  12 3
memory_unit          lock256                                   7  12 3
memory_unit          lock384                                   7  12 3
memory_unit          lock512                                   7  12 3
memory_unit          lookup                                    7  26 0
memory_unit          mask_compare_write18                      7  35 2
memory_unit          mask_compare_write20                      7  35 2
memory_unit          mask_compare_write32                      7  35 0
memory_unit          mask_compare_write64                      7  35 0
memory_unit          mask_compare_write_or_incr                7  34 2
memory_unit          memory_lock                               7  14 2
memory_unit          meter                                     7  30 2
memory_unit          microq128_get                             7  13 0
memory_unit          microq128_pop                             7  13 1
memory_unit          microq128_put                             7  13 2
memory_unit          microq256_get                             7  13 0
memory_unit          microq256_pop                             7  13 1
memory_unit          microq256_put                             7  13 2
memory_unit          packet_add_packet                         7  38 2
memory_unit          packet_add_thread                         7  39 3
memory_unit          packet_alloc                              7  39 0
memory_unit          packet_alloc_poll                         7  39 2
memory_unit          packet_credit_get                         7  39 1
memory_unit          packet_free                               7  40 0
memory_unit          packet_free_and_return_pointer            7  40 2
memory_unit          packet_free_and_signal                    7  40 1
memory_unit          packet_read_memory_status                 7  41 0
memory_unit          packet_read_packet_queue                  7  41 2
memory_unit          packet_read_packet_status                 7  38 1
memory_unit          packet_read_work_queue                    7  41 1
memory_unit          packet_return_pointer                     7  40 3
memory_unit          packet_wait_packet_status                 7  38 0
memory_unit          pe_dma_from_memory_buffer                 7  44 0
memory_unit          pe_dma_from_memory_buffer_le              7  44 1
memory_unit          pe_dma_from_memory_buffer_le_swap         7  44 3
memory_unit          pe_dma_from_memory_buffer_swap            7  44 2
memory_unit          pe_dma_from_memory_indirect               7  42 0
memory_unit          pe_dma_from_memory_indirect_free          7  42 2
memory_unit          pe_dma_from_memory_indirect_free_swap     7  42 3
memory_unit          pe_dma_from_memory_indirect_swap          7  42 1
memory_unit          pe_dma_to_memory_buffer                   7  45 0
memory_unit          pe_dma_to_memory_buffer_le                7  45 1
memory_unit          pe_dma_to_memory_buffer_le_swap           7  45 3
memory_unit          pe_dma_to_memory_buffer_swap              7  45 2
memory_unit          pe_dma_to_memory_indirect                 7  43 0
memory_unit          pe_dma_to_memory_indirect_free            7  43 2
memory_unit          pe_dma_to_memory_indirect_free_swap       7  43 3
memory_unit          pe_dma_to_memory_indirect_swap            7  43 1
memory_unit          pe_nbi_queue_depth_read                   7  46 2
memory_unit          pe_nbi_queue_depth_update                 7  46 0
memory_unit          pe_nbi_squencer_status_read               7  46 3
memory_unit          pe_nbi_squencer_status_update             7  46 1
memory_unit          pop                                       7  22 0
memory_unit          pop_eop                                   7  22 1
memory_unit          pop_freely                                7  22 2
memory_unit          pop_safe                                  7  22 2
memory_unit          push_qdesc                                7  16 2
memory_unit          put                                       7  20 0
memory_unit          qadd_thread                               7  19 1
memory_unit          qadd_work                                 7  19 2
memory_unit          qadd_work_imm                             7  19 3
memory_unit          queue128_lock                             7  14 0
memory_unit          queue128_unlock                           7  14 1
memory_unit          queue256_lock                             7  14 0
memory_unit          queue256_unlock                           7  14 1
memory_unit          rd_qdesc                                  7  16 0
memory_unit          read                                      7   0 0
memory_unit          read128                                   7  32 0
memory_unit          read128_be                                7  32 0
memory_unit          read128_le                                7  32 1
memory_unit          read128_swap                              7  32 2
memory_unit          read128_swap_be                           7  32 2
memory_unit          read128_swap_le                           7  32 3
memory_unit          read32                                    7  28 0
memory_unit          read32_be                                 7  28 0
memory_unit          read32_le                                 7  28 1
memory_unit          read32_swap                               7  28 2
memory_unit          read32_swap_be                            7  28 2
memory_unit          read32_swap_le                            7  28 3
memory_unit          read8                                     7   3 1
memory_unit          read8_be                                  7   3 1
memory_unit          read_atomic                               7  34 0
memory_unit          read_be                                   7   0 0
memory_unit          read_le                                   7   0 1
memory_unit          read_queue                                7  18 0
memory_unit          read_queue_ring                           7  18 1
memory_unit          read_swap                                 7   0 2
memory_unit          read_swap_be                              7   0 2
memory_unit          read_swap_le                              7   0 3
memory_unit          release_ticket                            7  11 0
memory_unit          release_ticket_ind                        7  11 1
memory_unit          set                                       7   5 0
memory_unit          set_imm                                   7   5 2
memory_unit          stats_log                                 7  24 0
memory_unit          stats_log_event                           7  24 2
memory_unit          stats_log_sat                             7  24 1
memory_unit          stats_log_sat_event                       7  24 3
memory_unit          stats_push                                7  25 0
memory_unit          stats_push_clear                          7  25 1
memory_unit          sub                                       7   9 0
memory_unit          sub64                                     7   9 0
memory_unit          sub64_imm                                 7   9 2
memory_unit          sub64_imm_sat                             7  10 2
memory_unit          sub64_sat                                 7  10 0
memory_unit          sub_imm                                   7   9 2
memory_unit          sub_imm_sat                               7  10 2
memory_unit          sub_sat                                   7  10 0
memory_unit          subsat                                    7  10 0
memory_unit          subsat64                                  7  10 0
memory_unit          subsat64_imm                              7  10 2
memory_unit          subsat_imm                                7  10 2
memory_unit          swap                                      7   4 1
memory_unit          swap_imm                                  7   4 3
memory_unit          tcam128_lookup16                          7  12 1
memory_unit          tcam128_lookup24                          7  12 1
memory_unit          tcam128_lookup32                          7  12 1
memory_unit          tcam128_lookup8                           7  12 1
memory_unit          tcam256_lookup16                          7  12 1
memory_unit          tcam256_lookup24                          7  12 1
memory_unit          tcam256_lookup32                          7  12 1
memory_unit          tcam256_lookup8                           7  12 1
memory_unit          tcam384_lookup16                          7  12 1
memory_unit          tcam384_lookup24                          7  12 1
memory_unit          tcam384_lookup32                          7  12 1
memory_unit          tcam384_lookup8                           7  12 1
memory_unit          tcam512_lookup16                          7  12 1
memory_unit          tcam512_lookup24                          7  12 1
memory_unit          tcam512_lookup32                          7  12 1
memory_unit          tcam512_lookup8                           7  12 1
memory_unit          tcam_lookup                               7  12 1
memory_unit          test_add                                  7   7 1
memory_unit          test_add32_var_sat_metering               7  30 1
memory_unit          test_add64                                7   7 1
memory_unit          test_add64_imm                            7   7 3
memory_unit          test_add64_var_sat_metering               7  30 1
memory_unit          test_add_imm                              7   7 3
memory_unit          test_addsat                               7   8 1
memory_unit          test_addsat64                             7   8 1
memory_unit          test_addsat64_imm                         7   8 3
memory_unit          test_addsat_imm                           7   8 3
memory_unit          test_and_add                              7   7 1
memory_unit          test_and_add64                            7   7 1
memory_unit          test_and_add64_imm                        7   7 3
memory_unit          test_and_add64_imm_sat                    7   8 3
memory_unit          test_and_add64_sat                        7   8 1
memory_unit          test_and_add_imm                          7   7 3
memory_unit          test_and_add_imm_sat                      7   8 3
memory_unit          test_and_add_sat                          7   8 1
memory_unit          test_and_clr                              7   6 1
memory_unit          test_and_clr_imm                          7   6 3
memory_unit          test_and_compare_write                    7  34 3
memory_unit          test_and_set                              7   5 1
memory_unit          test_and_set_imm                          7   5 3
memory_unit          test_and_sub                              7   9 1
memory_unit          test_and_sub64                            7   9 1
memory_unit          test_and_sub64_imm                        7   9 3
memory_unit          test_and_sub64_imm_sat                    7  10 3
memory_unit          test_and_sub64_sat                        7  10 1
memory_unit          test_and_sub_imm                          7   9 3
memory_unit          test_and_sub_imm_sat                      7  10 3
memory_unit          test_and_sub_sat                          7  10 1
memory_unit          test_and_xor                              7  15 1
memory_unit          test_and_xor_imm                          7  15 3
memory_unit          test_clr                                  7   6 1
memory_unit          test_clr_imm                              7   6 3
memory_unit          test_compare_write_or_incr                7  34 3
memory_unit          test_mask_compare_write18                 7  35 3
memory_unit          test_mask_compare_write20                 7  35 3
memory_unit          test_mask_compare_write32                 7  35 1
memory_unit          test_mask_compare_write64                 7  35 1
memory_unit          test_mask_compare_write_32_diff_swap      7  34 1
memory_unit          test_mask_compare_write_64_diff_swap      7  34 1
memory_unit          test_set                                  7   5 1
memory_unit          test_set_imm                              7   5 3
memory_unit          test_sub                                  7   9 1
memory_unit          test_sub64                                7   9 1
memory_unit          test_sub64_imm                            7   9 3
memory_unit          test_sub_imm                              7   9 3
memory_unit          test_subsat                               7  10 1
memory_unit          test_subsat64                             7  10 1
memory_unit          test_subsat64_imm                         7  10 3
memory_unit          test_subsat_imm                           7  10 3
memory_unit          test_xor                                  7  15 1
memory_unit          test_xor_imm                              7  15 3
memory_unit          ticket_release                            7  11 0
memory_unit          ticket_release_ind                        7  11 1
memory_unit          wr_qdesc                                  7  16 1
memory_unit          write                                     7   1 0
memory_unit          write128                                  7  33 0
memory_unit          write128_be                               7  33 0
memory_unit          write128_le                               7  33 1
memory_unit          write128_swap                             7  33 2
memory_unit          write128_swap_be                          7  33 2
memory_unit          write128_swap_le                          7  33 3
memory_unit          write32                                   7  31 0
memory_unit          write32_be                                7  31 0
memory_unit          write32_le                                7  31 1
memory_unit          write32_swap                              7  31 2
memory_unit          write32_swap_be                           7  31 2
memory_unit          write32_swap_le                           7  31 3
memory_unit          write8                                    7   2 0
memory_unit          write8_be                                 7   2 0
memory_unit          write8_le                                 7   2 1
memory_unit          write8_swap                               7   2 2
memory_unit          write8_swap_be                            7   2 2
memory_unit          write8_swap_le                            7   2 3
memory_unit          write_atomic                              7   4 0
memory_unit          write_atomic_imm                          7   4 2
memory_unit          write_be                                  7   1 0
memory_unit          write_le                                  7   1 1
memory_unit          write_queue                               7  18 2
memory_unit          write_queue_ring                          7  18 3
memory_unit          write_swap                                7   1 2
memory_unit          write_swap_be                             7   1 2
memory_unit          write_swap_le                             7   1 3
memory_unit          xor                                       7  15 0
memory_unit          xor_imm                                   7  15 2
cluster_scratch      decr                                      15  7 0
cluster_scratch      decr64                                    15  7 1
cluster_scratch      incr                                      15  5 0
cluster_scratch      incr64                                    15  5 1
cluster_scratch      add                                       15  4 0
cluster_scratch      add64                                     15  4 1
cluster_scratch      add64_imm                                 15  5 1
cluster_scratch      add_imm                                   15  5 0
cluster_scratch      add_imm_sat                               15  5 2
cluster_scratch      add_sat                                   15  4 2
cluster_scratch      add_tail                                  15 10 3
cluster_scratch      addsat                                    15  4 2
cluster_scratch      addsat_imm                                15  5 2
cluster_scratch      cam_lookup16                              15 12 2
cluster_scratch      cam_lookup16_add                          15 12 3
cluster_scratch      cam_lookup24                              15 11 2
cluster_scratch      cam_lookup24_add                          15 11 3
cluster_scratch      cam_lookup24_add_inc                      15 16 2
cluster_scratch      cam_lookup32                              15 11 0
cluster_scratch      cam_lookup32_add                          15 11 1
cluster_scratch      cam_lookup32_add_extend                   15 16 3
cluster_scratch      cam_lookup32_add_lock                     15 16 1
cluster_scratch      cam_lookup8                               15 12 0
cluster_scratch      cam_lookup8_add                           15 12 1
cluster_scratch      clr                                       15  2 1
cluster_scratch      clr_imm                                   15  3 1
cluster_scratch      cmp_rw                                    15  0 2
cluster_scratch      fast_journal                              15 25 3
cluster_scratch      get                                       15  9 0
cluster_scratch      get_safe                                  15  9 2
cluster_scratch      hash_mask                                 15  8 2
cluster_scratch      hash_mask_clear                           15  8 3
cluster_scratch      hash_with_push                            15 26 0
cluster_scratch      journal                                   15 10 2
cluster_scratch      meter                                     15 17 0
cluster_scratch      pop                                       15  9 1
cluster_scratch      pop_safe                                  15  9 3
cluster_scratch      put                                       15 10 0
cluster_scratch      queue_lock                                15  8 0
cluster_scratch      queue_unlock                              15  8 1
cluster_scratch      read                                      15  0 0
cluster_scratch      read_be                                   15  0 0
cluster_scratch      read_le                                   15  0 1
cluster_scratch      reflect_from_sig_both                     15 14 2
cluster_scratch      reflect_from_sig_dst                      15 14 1
cluster_scratch      reflect_from_sig_src                      15 14 0
cluster_scratch      reflect_read_sig_both                     15 15 2
cluster_scratch      reflect_read_sig_local                    15 15 1
cluster_scratch      reflect_read_sig_remote                   15 15 0
cluster_scratch      reflect_to_sig_both                       15 15 2
cluster_scratch      reflect_to_sig_dst                        15 15 1
cluster_scratch      reflect_to_sig_src                        15 15 0
cluster_scratch      reflect_write_sig_both                    15 14 2
cluster_scratch      reflect_write_sig_local                   15 14 0
cluster_scratch      reflect_write_sig_remote                  15 14 1
cluster_scratch      ring_add_to_tail_ptr                      15 10 3
cluster_scratch      ring_get                                  15  9 0
cluster_scratch      ring_get_freely                           15  9 2
cluster_scratch      ring_journal                              15 10 2
cluster_scratch      ring_ordered_lock                         15 24 2
cluster_scratch      ring_ordered_unlock                       15 24 3
cluster_scratch      ring_pop                                  15  9 1
cluster_scratch      ring_pop_freely                           15  9 3
cluster_scratch      ring_put                                  15 10 0
cluster_scratch      ring_put_imm                              15 25 2
cluster_scratch      ring_put_with_push                        15 10 1
cluster_scratch      ring_read                                 15 24 0
cluster_scratch      ring_workq_add_thread                     15 25 0
cluster_scratch      ring_workq_add_work                       15 25 1
cluster_scratch      ring_workq_add_work_imm                   15 14 3
cluster_scratch      ring_write                                15 24 1
cluster_scratch      set                                       15  2 0
cluster_scratch      set_imm                                   15  3 0
cluster_scratch      statistic                                 15 17 2
cluster_scratch      statistic_imm                             15 17 3
cluster_scratch      sub                                       15  6 0
cluster_scratch      sub64                                     15  6 1
cluster_scratch      sub64_imm                                 15  7 1
cluster_scratch      sub_imm                                   15  7 0
cluster_scratch      sub_imm_sat                               15  7 2
cluster_scratch      sub_sat                                   15  6 2
cluster_scratch      subsat                                    15  6 2
cluster_scratch      subsat_imm                                15  7 2
cluster_scratch      swap                                      15  0 2
cluster_scratch      tcam_lookup                               15 13 0
cluster_scratch      tcam_lookup16                             15 13 2
cluster_scratch      tcam_lookup24                             15 13 1
cluster_scratch      tcam_lookup32                             15 13 0
cluster_scratch      tcam_lookup8                              15 13 3
cluster_scratch      tcam_lookup_byte                          15 13 3
cluster_scratch      test_add                                  15 20 0
cluster_scratch      test_add64                                15 20 1
cluster_scratch      test_add64_imm                            15 21 1
cluster_scratch      test_add_imm                              15 21 0
cluster_scratch      test_addsat                               15 20 2
cluster_scratch      test_addsat_imm                           15 21 2
cluster_scratch      test_and_add_imm_sat                      15 21 2
cluster_scratch      test_and_add_sat                          15 20 2
cluster_scratch      test_and_clr                              15  2 3
cluster_scratch      test_and_clr_imm                          15  3 3
cluster_scratch      test_and_compare_write                    15  0 2
cluster_scratch      test_and_set                              15  2 2
cluster_scratch      test_and_set_imm                          15  3 2
cluster_scratch      test_and_sub_imm_sat                      15 23 2
cluster_scratch      test_and_sub_sat                          15 22 2
cluster_scratch      test_clr                                  15  2 3
cluster_scratch      test_clr_imm                              15  3 3
cluster_scratch      test_compare_write                        15  0 2
cluster_scratch      test_set                                  15  2 2
cluster_scratch      test_set_imm                              15  3 2
cluster_scratch      test_sub                                  15 22 0
cluster_scratch      test_sub64                                15 22 1
cluster_scratch      test_sub64_imm                            15 23 1
cluster_scratch      test_sub_imm                              15 23 0
cluster_scratch      test_subsat                               15 22 2
cluster_scratch      test_subsat_imm                           15 23 2
cluster_scratch      write                                     15  1 0
cluster_scratch      write8                                    15  1 2
cluster_scratch      write8_be                                 15  1 2
cluster_scratch      write8_le                                 15  1 3
cluster_scratch      write_be                                  15  1 0
cluster_scratch      write_le                                  15  1 1
cluster_scratch      xor                                       15  0 3
nbi                  packet_ready_drop                         1   3 0
nbi                  packet_ready_multicast_dont_free          1   3 2
nbi                  packet_ready_multicast_free_on_last       1   3 3
nbi                  packet_ready_unicast                      1   3 1
nbi                  pcie_reorder                              1   4 0
nbi                  pcie_reorder_vm_qos                       1   4 1
nbi                  read                                      1   0 0
nbi                  write                                     1   1 0
pcie                 read                                      9   0 0
pcie                 read_int                                  9   2 0
pcie                 read_pci                                  9   2 0
pcie                 read_rid                                  9   0 1
pcie                 write                                     9   1 0
pcie                 write_int                                 9   3 0
pcie                 write_pci                                 9   3 0
pcie                 write_rid                                 9   1 1
pcie                 write_vdm                                 9   1 2
crypto               read                                      12  0 0
crypto               write                                     12  1 0
crypto               write_fifo                                12  2 0
arm                  read                                      10  0 0
arm                  write                                     10  1 0
ct                   ctnn_write                                14  1 2
ct                   interthread_signal                        14  0 2
ct                   reflect_read_none                         14  2 0
ct                   reflect_read_sig_both                     14  2 3
ct                   reflect_read_sig_init                     14  2 1
ct                   reflect_read_sig_remote                   14  2 2
ct                   reflect_write_none                        14  3 0
ct                   reflect_write_sig_both                    14  3 3
ct                   reflect_write_sig_init                    14  3 1
ct                   reflect_write_sig_remote                  14  3 2
ct                   xpb_read                                  14  0 0
ct                   xpb_write                                 14  1 0
